### ISSUE TITLE
Global retention time alignment for DDA data.

### ISSUE THREAD

**Issue by Peer2011** [Roestlab/DIAlignR#38]
Dear people of the Röstlab, 

Would it be possible to use your algorithm DIAalignR as well for global retention time alignment of DDA data. I would like to perform a global retention time alignment over 410 independent runs to correct the retention time and imrpove FDR for LFQ afterwards and thus would like to input mzml files which I correct and then afterwards output as modified mzml files with corrected retention time. If you have any other idea how to do this please let me know.

Best, Peer

**Comment by shubham1637** [comment]
Hi,
   It is possible to use global alignment for fixing retention time in DDA samples. Our traditional workflow uses SWATH files, finds peaks and score them. The retention time alignment function then uses high-scoring peaks to find a reasonable retention-time mapping. 
   Since, you have mzML spectra file, I would suggest to run a software for peak-picking and peak-scoring. You can use MaxQuant or OpenMS. You can then select high-scoring peaks to find the RT-mapping function. Post-mapping, You need to mutate the files to fix the retention times. I am not sure what you are trying to achieve with correcting the retention time in mzML, becuase, DDA mostly uses Spectrum-matching for the peptide identification.
  Hope this helps.

Best,
Shubham Gupta
